Feature/issues
digma-ai/digma-ui pull request #928
Opened 2024-07-08 22:09 UTC by opoliarush

#813

2024-07-08 22:12 UTC, opoliarush commented on src/components/Insights/index.tsx
> +            setIssuesFilterQuery(filters);
*

2024-07-10 12:12 UTC, kshmidt-digma commented on src/components/Insights/Issues/IssuesFilter/tracking.ts
> +    CLEAR_ALL_FILTERS_BUTTON_CLICKED: "clear filters all button clicked"
```suggestion
    CLEAR_ALL_FILTERS_BUTTON_CLICKED: "clear all filters button clicked"
```

2024-07-10 12:34 UTC, kshmidt-digma requested changes

2024-07-10 12:34 UTC, kshmidt-digma commented on src/components/Insights/Issues/IssuesFilter/index.tsx
> +      isUndefined(previousPersistedFilters) &&
```suggestion
     !previousPersistedFilters &&
```

2024-07-10 12:34 UTC, kshmidt-digma commented on src/components/common/v3/Select/index.tsx
> +  );
can be removed

2024-07-10 14:44 UTC, kshmidt-digma approved these changes

2024-07-10 17:52 UTC, kshmidt-digma approved these changes

2024-07-10 18:07 UTC, merged